language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      python: 3.6

addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev
    - libsm-dev
    - libgtk-3-dev
    - libwebkitgtk-3.0-dev

# command to install dependencies
install:
  - make init-accelerated

# command to run tests
script:
  - make test
  - make dist