language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      python: 3.6

addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev
    - libsm-dev
    - libgtk-3-dev
    - libwebkitgtk-3.0-dev
    - mesa-utils
    - xvfb


before_install:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

# command to install dependencies
install:
  - make init-accelerated
  - pip install coveralls

# command to run tests
script:
  - make test
  - make dist

after_success:
  - PYTHONPATH=./lib:. coverage run --source=BeeVeeH -m lib.pytest --ignore=lib
  - coveralls